source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ANShareViewController_Example', :exclusive => true do
  pod "ANShareViewController", :path => "../"
end

target 'ANShareViewController_Tests', :exclusive => true do
  pod "ANShareViewController", :path => "../"

  
end
